import assert from "node:assert/strict";
import test from "node:test";
import { claimCodeExport,csvCell,processCodeExport } from "../src/code-export-worker.mjs";

const config={OBJECT_STORAGE_BUCKET:"exports"};
const row={id:"10000000-0000-0000-0000-000000000001",tenant_id:"20000000-0000-0000-0000-000000000001",code_batch_id:"30000000-0000-0000-0000-000000000001"};

test("CSV cells prevent spreadsheet formula injection and preserve delimiters",()=>{assert.equal(csvCell("=cmd()"),"'=cmd()");assert.equal(csvCell("a,b"),'"a,b"');assert.equal(csvCell('a"b'),'"a""b"');});

test("code export claim uses skip locked and recovers an interrupted export",async()=>{const calls=[],db={transaction:async work=>work({query:async sql=>{calls.push(sql);return sql.includes("SELECT *")?{rowCount:0,rows:[]}:{rowCount:1,rows:[]};}})};assert.equal(await claimCodeExport(db),null);assert.match(calls[0],/FOR UPDATE SKIP LOCKED/);assert.match(calls[0],/export_status='EXPORTING' AND export_locked_at<now\(\)-interval '15 minutes'/);});

test("code export streams bounded immutable pages to object storage and stores integrity metadata",async()=>{const calls=[],items=[{id:"40000000-0000-0000-0000-000000000001",code:"https://id.example/01/1/21/1",level:"ITEM",lot:"LOT-1",product_id:"50000000-0000-0000-0000-000000000001",created_at:"2026-08-28T00:00:00Z"},{id:"40000000-0000-0000-0000-000000000002",code:"https://id.example/01/1/21/2",level:"ITEM",lot:"LOT-1",product_id:"50000000-0000-0000-0000-000000000001",created_at:"2026-08-28T00:00:01Z"}];let pageNumber=0,bodyText="",uploadParams;class FakeUpload{constructor(options){uploadParams=options.params;}async done(){for await(const chunk of uploadParams.Body)bodyText+=chunk.toString("utf8");}}const db={query:async(sql,params)=>{calls.push({sql,params});if(sql.startsWith("SELECT id")){const item=items[pageNumber++];return{rowCount:pageNumber===1?5000:1,rows:[item]};}return{rowCount:1,rows:[]};}};assert.equal(await processCodeExport(db,config,row,{storage:{},UploadClass:FakeUpload}),true);assert.equal(uploadParams.Bucket,"exports");assert.match(uploadParams.Key,new RegExp(`tenants/${row.tenant_id}/code-jobs/${row.id}/codes\\.csv`));assert.match(bodyText,/^\uFEFFcode,level,lot,product_id,created_at/);assert.match(bodyText,/\/21\/1/);assert.match(bodyText,/\/21\/2/);const selects=calls.filter(call=>call.sql.startsWith("SELECT id"));assert.equal(selects.length,2);assert.equal(selects[1].params[2],items[0].id);const update=calls.at(-1);assert.match(update.sql,/export_status='COMPLETED'/);assert.equal(update.params[2],Buffer.byteLength(bodyText));assert.match(update.params[3],/^[a-f0-9]{64}$/);assert.equal(update.params[4],row.tenant_id);});

test("failed code export is retried and eventually dead-lettered",async()=>{let update;class FailedUpload{async done(){throw new Error("storage offline");}}const db={query:async(sql,params)=>{update={sql,params};return{rowCount:0,rows:[]};}};assert.equal(await processCodeExport(db,config,{...row,export_attempts:9},{storage:{},UploadClass:FailedUpload}),false);assert.match(update.sql,/export_attempts\+1>=10 THEN 'DEAD_LETTER'/);assert.deepEqual(update.params,[row.id,"storage offline",row.tenant_id]);});
