import assert from "node:assert/strict";
import test from "node:test";
import { captureEpcisDocument,queryEpcisEvents } from "../src/epcis-client.mjs";

const headers=values=>({get:name=>values[String(name).toLowerCase()]||null});
test("OpenEPCIS capture contract sends an exact EPCIS JSON document",async()=>{const document={"@context":["https://ref.gs1.org/standards/epcis/epcis-context.jsonld"],type:"EPCISDocument",schemaVersion:"2.0",creationDate:"2026-08-28T00:00:00.000Z",epcisBody:{eventList:[]}};let request;const result=await captureEpcisDocument("https://epcis.example.cn/root/",document,{outboxId:"event-1",bearerToken:"epcis-secret-token",fetchImpl:async(url,options)=>{request={url:String(url),options};return{ok:true,status:202,headers:headers({location:"/capture/123"})};}});assert.equal(request.url,"https://epcis.example.cn/root/epcis/capture");assert.equal(request.options.headers.accept,"application/json");assert.equal(request.options.headers["content-type"],"application/json");assert.equal(request.options.headers["GS1-EPCIS-Version"],"2.0.0");assert.equal(request.options.headers["GS1-CBV-Version"],"2.0.0");assert.equal(request.options.headers.authorization,"Bearer epcis-secret-token");assert.equal(request.options.headers["x-reliacode-outbox-id"],"event-1");assert.deepEqual(JSON.parse(request.options.body),document);assert.equal(result.captureId,"/capture/123");});

test("OpenEPCIS query contract uses bounded standard parameters and parses pagination",async()=>{let requestUrl;const payload={type:"EPCISQueryDocument",epcisBody:{queryResults:{resultsBody:{eventList:[{type:"ObjectEvent",eventID:"urn:uuid:event-1"}]}}}};const result=await queryEpcisEvents("https://epcis.example.cn/",{matchEpc:"https://id.example/01/09506000134352/21/ABC",eventType:"ObjectEvent",eventTimeFrom:"2026-08-01T00:00:00.000Z",limit:250},{fetchImpl:async url=>{requestUrl=new URL(url);return{ok:true,status:200,headers:headers({"gs1-next-page-token":"next-1"}),json:async()=>payload};}});assert.equal(requestUrl.pathname,"/epcis/events");assert.equal(requestUrl.searchParams.get("MATCH_epc"),"https://id.example/01/09506000134352/21/ABC");assert.equal(requestUrl.searchParams.get("GE_eventTime"),"2026-08-01T00:00:00.000Z");assert.equal(requestUrl.searchParams.get("perPage"),"250");assert.equal(result.nextPageToken,"next-1");assert.equal(result.events[0].eventID,"urn:uuid:event-1");});

test("OpenEPCIS contract rejects malformed query documents and bounds error bodies",async()=>{await assert.rejects(()=>queryEpcisEvents("https://epcis.example.cn/",{limit:100},{fetchImpl:async()=>({ok:true,status:200,headers:headers({}),json:async()=>({type:"not-epcis"})})}),error=>error.name==="ZodError");await assert.rejects(()=>captureEpcisDocument("https://epcis.example.cn/",{type:"EPCISDocument"},{outboxId:"one",fetchImpl:async()=>({ok:false,status:503,headers:headers({"x-request-id":"remote-1"}),text:async()=>"x".repeat(1000)})}),error=>error.code==="OPEN_EPCIS_ERROR"&&error.message.includes("remote-1")&&error.message.length<600);});
