import assert from "node:assert/strict";
import test from "node:test";
import { buildApp } from "../src/app.mjs";
import { loadConfig } from "../src/config.mjs";

const ids={tenant:"11111111-1111-4111-8111-111111111111",organization:"22222222-2222-4222-8222-222222222222",user:"44444444-4444-4444-8444-444444444444",risk:"55555555-5555-4555-8555-555555555555",recall:"66666666-6666-4666-8666-666666666666"};
const headers={"x-reliacode-principal":JSON.stringify({sub:ids.user,tenant_id:ids.tenant,organization_id:ids.organization,role:"BRAND_ADMIN"}),"idempotency-key":"governance-route-command-0001"};
const config=loadConfig({NODE_ENV:"test",DATABASE_URL:"postgres://unused",AUTH_MODE:"development",CORS_ORIGINS:"http://localhost:4173",LOG_LEVEL:"silent"});
function database({recallMatches=0}={}){const calls=[],client={query:async(sql,params=[])=>{calls.push({sql,params});if(sql.includes("FROM idempotency_records"))return{rowCount:0,rows:[]};if(sql.includes("FROM risk_cases WHERE"))return{rowCount:1,rows:[{id:ids.risk,status:"OPEN",risk_type:"TEST_RISK"}]};if(sql.includes("UPDATE risk_cases"))return{rowCount:1,rows:[{id:ids.risk,status:"REJECTED"}]};if(sql.includes("SELECT * FROM recalls"))return{rowCount:1,rows:[{id:ids.recall,status:"DRAFT",reference:"R-1",title:"Recall",scope:{productIds:["77777777-7777-4777-8777-777777777777"],lots:[]}}]};if(sql.includes("INSERT INTO recall_objects"))return{rowCount:recallMatches,rows:Array.from({length:recallMatches},()=>({object_id:"77777777-7777-4777-8777-777777777777"}))};if(sql.includes("UPDATE recalls"))return{rowCount:1,rows:[{id:ids.recall,status:"ACTIVE",reference:"R-1",title:"Recall",activated_at:"2026-08-28T00:00:00Z"}]};return{rowCount:1,rows:[{}]};}};return{calls,query:async(sql,params)=>{calls.push({sql,params});if(sql.includes("SELECT EXISTS"))return{rowCount:1,rows:[{active:true}]};return client.query(sql,params);},transaction:work=>work(client)};}

test("risk listing and decisions are tenant scoped",async t=>{const db=database(),app=await buildApp({config,db});t.after(()=>app.close());const list=await app.inject({method:"GET",url:"/api/v1/risk-cases?status=OPEN&severity=HIGH&limit=20",headers});assert.equal(list.statusCode,200,list.body);const decision=await app.inject({method:"POST",url:`/api/v1/risk-cases/${ids.risk}/decisions`,headers,payload:{action:"REJECT",reason:"reject after governed evidence review"}});assert.equal(decision.statusCode,200,decision.body);const listCall=db.calls.find(call=>call.sql.includes("FROM risk_cases rc"));assert.deepEqual(listCall.params.slice(0,3),[ids.tenant,"OPEN","HIGH"]);const update=db.calls.find(call=>call.sql.includes("UPDATE risk_cases"));assert.equal(update.sql.includes("WHERE tenant_id=$4 AND id=$5"),true);assert.equal(update.params[3],ids.tenant);assert.ok(db.calls.some(call=>call.sql.includes("INSERT INTO webhook_deliveries")));});

test("an empty recall scope cannot be activated",async t=>{const db=database(),app=await buildApp({config,db});t.after(()=>app.close());const response=await app.inject({method:"POST",url:`/api/v1/recalls/${ids.recall}/activate`,headers,payload:{auditReason:"activate governed recall"}});assert.equal(response.statusCode,409,response.body);assert.equal(response.json().code,"RECALL_SCOPE_EMPTY");assert.equal(db.calls.some(call=>call.sql.includes("UPDATE recalls")),false);});

test("recall activation is tenant scoped and queues its webhook",async t=>{const db=database({recallMatches:1}),app=await buildApp({config,db});t.after(()=>app.close());const response=await app.inject({method:"POST",url:`/api/v1/recalls/${ids.recall}/activate`,headers,payload:{auditReason:"activate governed recall"}});assert.equal(response.statusCode,200,response.body);assert.equal(response.json().objectCount,1);const update=db.calls.find(call=>call.sql.includes("UPDATE recalls"));assert.deepEqual(update.params,[ids.user,ids.tenant,ids.recall]);assert.ok(db.calls.some(call=>call.sql.includes("INSERT INTO webhook_deliveries")));});
