import assert from "node:assert/strict";
import test from "node:test";
import { buildApp } from "../src/app.mjs";
import { hashToken } from "../src/auth.mjs";
import { loadConfig } from "../src/config.mjs";

const config=loadConfig({NODE_ENV:"test",DATABASE_URL:"postgres://unused",AUTH_MODE:"development",LOG_LEVEL:"silent"});
const tenantId="11111111-1111-4111-8111-111111111111",organizationId="22222222-2222-4222-8222-222222222222",caseId="33333333-3333-4333-8333-333333333333",userId="44444444-4444-4444-8444-444444444444";
const platform=id=>({"x-reliacode-principal":JSON.stringify({sub:id,tenant_id:tenantId,organization_id:organizationId,role:"PLATFORM_OPERATOR"}),"idempotency-key":`manual-recovery-${id}`});
const pending={id:caseId,tenant_id:tenantId,user_id:userId,status:"PENDING",requested_by:"operator-a",request_reason:"lost every authenticator",reviewed_by:null,review_reason:null,created_at:new Date().toISOString()};

test("manual recovery requires a different platform reviewer",async t=>{const db={query:async sql=>sql.includes("SELECT EXISTS")?{rowCount:1,rows:[{active:true}]}:{rowCount:0,rows:[]},transaction:async work=>work({query:async sql=>{if(sql.includes("FROM platform_idempotency_records"))return{rowCount:0,rows:[]};if(sql.includes("FROM platform_account_recovery_cases WHERE id"))return{rowCount:1,rows:[pending]};return{rowCount:1,rows:[]};}})};const app=await buildApp({config,db});t.after(()=>app.close());const response=await app.inject({method:"POST",url:`/api/v1/platform/account-recovery-cases/${caseId}/decision`,headers:platform("operator-a"),payload:{action:"APPROVE",reason:"identity checked"}});assert.equal(response.statusCode,403);assert.equal(response.json().code,"DUAL_CONTROL_REQUIRED");});

test("approval returns a credential once but persists only its hash",async t=>{const calls=[],approved={...pending,status:"APPROVED",reviewed_by:"operator-b",review_reason:"identity checked",recovery_expires_at:new Date(Date.now()+1_800_000).toISOString()};const db={query:async sql=>sql.includes("SELECT EXISTS")?{rowCount:1,rows:[{active:true}]}:{rowCount:0,rows:[]},transaction:async work=>work({query:async(sql,params=[])=>{calls.push({sql,params});if(sql.includes("FROM platform_idempotency_records"))return{rowCount:0,rows:[]};if(sql.includes("FROM platform_account_recovery_cases WHERE id"))return{rowCount:1,rows:[pending]};if(sql.startsWith("UPDATE platform_account_recovery_cases SET status='APPROVED'"))return{rowCount:1,rows:[approved]};return{rowCount:1,rows:[]};}})};const app=await buildApp({config,db});t.after(()=>app.close());const response=await app.inject({method:"POST",url:`/api/v1/platform/account-recovery-cases/${caseId}/decision`,headers:platform("operator-b"),payload:{action:"APPROVE",reason:"identity checked"}});assert.equal(response.statusCode,200);const credential=response.json().recoveryCredential;assert.ok(credential.length>=43);const update=calls.find(call=>call.sql.startsWith("UPDATE platform_account_recovery_cases SET status='APPROVED'"));assert.equal(update.params[2],hashToken(credential));assert.equal(update.params.includes(credential),false);const idempotency=calls.find(call=>call.sql.startsWith("INSERT INTO platform_idempotency_records"));assert.equal(JSON.stringify(idempotency.params).includes(credential),false);});

test("manual recovery confirmation is anonymous, atomic, and revokes every session",async t=>{const calls=[],db={query:async(sql,params=[])=>{calls.push({sql,params});if(sql.includes("WITH expired AS"))return{rowCount:1,rows:[{id:caseId}]};throw new Error(`Unexpected SQL: ${sql}`);}};const app=await buildApp({config,db});t.after(()=>app.close());const credential="x".repeat(43),response=await app.inject({method:"POST",url:"/api/auth/manual-recovery/confirm",payload:{caseId,credential,newPassword:"new-secure-password-123"}});assert.equal(response.statusCode,200);assert.equal(response.json().sessionsRevoked,true);assert.equal(calls[0].params[1],hashToken(credential));assert.match(calls[0].sql,/status='EXPIRED'/);assert.match(calls[0].sql,/UPDATE admin_sessions/);assert.match(calls[0].sql,/MANUAL_RECOVERY_COMPLETED/);assert.doesNotMatch(JSON.stringify(calls[0].params),/new-secure-password-123/);});
