import assert from "node:assert/strict";
import { chromium } from "playwright";
import { testBaseUrl } from "./helpers.mjs";
const ids={tenant:"11111111-1111-4111-8111-111111111111",organization:"22222222-2222-4222-8222-222222222222",user:"44444444-4444-4444-8444-444444444444",risk:"55555555-5555-4555-8555-555555555555",recall:"66666666-6666-4666-8666-666666666666",product:"77777777-7777-4777-8777-777777777777"};
let risk={id:ids.risk,risk_type:"OBJECT_NOT_IN_SHIPMENT",severity:"HIGH",status:"OPEN",evidence:{objectCode:"OBJECT-RISK-1"},object_code:"OBJECT-RISK-1",event_type:"RECEIVING_STORE",created_at:"2026-08-28T00:00:00Z"},recall={id:ids.recall,reference:"RECALL-001",title:"Test recall",reason:"quality investigation",status:"DRAFT",scope:{productIds:[ids.product],lots:[]}},riskCommand=null,activationCommand=null;
const browser=await chromium.launch({headless:true}),context=await browser.newContext({viewport:{width:1280,height:900}}),page=await context.newPage();await page.route("**/runtime-config.js",route=>route.fulfill({contentType:"application/javascript",body:"window.RELIACODE_CONFIG=Object.freeze({apiBaseUrl:'',persistentWorkspace:false,domainApi:true});"}));
await page.route("**/api/**",async route=>{const request=route.request(),path=new URL(request.url()).pathname,json=body=>route.fulfill({status:200,contentType:"application/json",headers:{"x-csrf-token":"csrf-governance"},body:JSON.stringify(body)});if(path==="/api/auth/session")return json({csrfToken:"csrf-governance",user:{id:ids.user,name:"Governance Admin",tenantId:ids.tenant,organizationId:ids.organization,organizationName:"Brand 01",role:"BRAND_ADMIN",capabilities:["objects:read","events:read","risks:review","recalls:write"]}});if(path==="/api/v1/products")return json({items:[{id:ids.product,name:"Product 1",sku:"SKU-1",status:"ACTIVE"}]});if(path==="/api/v1/documents"||path==="/api/v1/devices"||path==="/api/v1/trace-events")return json({items:[],nextCursor:null});if(path==="/api/v1/risk-cases"&&request.method()==="GET")return json({items:[risk],nextCursor:null});if(path===`/api/v1/risk-cases/${ids.risk}/decisions`){riskCommand={headers:request.headers(),body:request.postDataJSON()};risk={...risk,status:riskCommand.body.action==='REJECT'?'REJECTED':'APPROVED',resolution_reason:riskCommand.body.reason};return json(risk);}if(path==="/api/v1/recalls"&&request.method()==="GET")return json({items:[recall]});if(path===`/api/v1/recalls/${ids.recall}/activate`){activationCommand={headers:request.headers(),body:request.postDataJSON()};recall={...recall,status:"ACTIVE"};return json({...recall,objectCount:12});}return route.fulfill({status:404,contentType:"application/json",body:JSON.stringify({message:`Unhandled ${request.method()} ${path}`})});});
await page.goto(testBaseUrl,{waitUntil:"networkidle"});await page.locator('[data-view="risk"]').click();assert.match(await page.locator('#risk').innerText(),/OBJECT_NOT_IN_SHIPMENT/);page.once('dialog',dialog=>dialog.accept('reject after reviewing shipment evidence'));await page.locator('[data-domain-risk][data-action="REJECT"]').click();await page.waitForFunction(()=>document.querySelector('#risk')?.textContent.includes('REJECTED'));assert.equal(riskCommand.body.action,'REJECT');assert.ok(riskCommand.headers['idempotency-key']);
await page.locator('[data-view="recalls"]').click();assert.match(await page.locator('#recalls').innerText(),/RECALL-001/);let dialogs=0;page.on('dialog',async dialog=>{dialogs+=1;if(dialog.type()==='prompt')await dialog.accept('activate after quality board approval');else await dialog.accept();});await page.locator('[data-recall-activate]').click();await page.waitForFunction(()=>document.querySelector('#recalls')?.textContent.includes('ACTIVE'));assert.equal(dialogs,2);assert.deepEqual(activationCommand.body,{auditReason:'activate after quality board approval'});assert.ok(activationCommand.headers['idempotency-key']);await browser.close();console.log('GOVERNANCE CONSOLE E2E PASS: risk decision and confirmed recall activation use governed APIs');
