import { z } from "zod";

const queryDocument=z.object({type:z.literal("EPCISQueryDocument"),epcisBody:z.object({queryResults:z.object({resultsBody:z.object({eventList:z.array(z.record(z.string(),z.unknown()))})})})}).passthrough();
function endpoint(baseUrl,path){return new URL(path,`${String(baseUrl).replace(/\/$/,"")}/`);}
async function errorFor(response){const requestId=response.headers?.get?.("x-request-id")||response.headers?.get?.("traceparent")||"unknown";let detail="";try{detail=(await response.text()).slice(0,500);}catch{}const error=new Error(`OpenEPCIS returned ${response.status} (request ${requestId}): ${detail}`);error.code="OPEN_EPCIS_ERROR";error.status=response.status;return error;}

const versionHeaders=Object.freeze({"GS1-EPCIS-Version":"2.0.0","GS1-CBV-Version":"2.0.0"});
export async function captureEpcisDocument(baseUrl,document,{outboxId,fetchImpl=fetch,timeoutMs=15_000}={}){const response=await fetchImpl(endpoint(baseUrl,"epcis/capture"),{method:"POST",headers:{accept:"application/json","content-type":"application/json",...versionHeaders,"x-reliacode-outbox-id":String(outboxId)},body:JSON.stringify(document),signal:AbortSignal.timeout(timeoutMs)});if(!response.ok)throw await errorFor(response);return{captureId:response.headers?.get?.("location")||response.headers?.get?.("x-request-id")||null,status:response.status};}

export async function queryEpcisEvents(baseUrl,input,{fetchImpl=fetch,timeoutMs=15_000}={}){const query=z.object({matchEpc:z.string().min(1).max(2048).optional(),eventType:z.enum(["ObjectEvent","AggregationEvent","TransactionEvent","TransformationEvent","AssociationEvent"]).optional(),eventTimeFrom:z.string().datetime({offset:true}).optional(),eventTimeTo:z.string().datetime({offset:true}).optional(),nextPageToken:z.string().min(1).max(2048).optional(),limit:z.number().int().min(1).max(1000).default(100)}).parse(input),url=endpoint(baseUrl,"epcis/events");if(query.matchEpc)url.searchParams.set("MATCH_epc",query.matchEpc);if(query.eventType)url.searchParams.set("eventType",query.eventType);if(query.eventTimeFrom)url.searchParams.set("GE_eventTime",query.eventTimeFrom);if(query.eventTimeTo)url.searchParams.set("LT_eventTime",query.eventTimeTo);if(query.nextPageToken)url.searchParams.set("nextPageToken",query.nextPageToken);url.searchParams.set("perPage",String(query.limit));const response=await fetchImpl(url,{headers:{accept:"application/json",...versionHeaders},signal:AbortSignal.timeout(timeoutMs)});if(!response.ok)throw await errorFor(response);const parsed=queryDocument.parse(await response.json());return{events:parsed.epcisBody.queryResults.resultsBody.eventList,nextPageToken:response.headers?.get?.("GS1-Next-Page-Token")||null,document:parsed};}
