const buckets=[0.1,0.25,0.5,1,2.5,5];
const observations=new Map();
function labels(method,route,status){return `method="${String(method).replaceAll('"','')}",route="${String(route).replaceAll('"','')}",status="${status}"`;}
export function observeHttpRequest(method,route,status,durationSeconds){const key=labels(method,route,status),current=observations.get(key)||{count:0,sum:0,buckets:buckets.map(()=>0)};current.count+=1;current.sum+=Number(durationSeconds)||0;buckets.forEach((limit,index)=>{if(durationSeconds<=limit)current.buckets[index]+=1;});observations.set(key,current);}
export async function renderMetrics(db){const lines=["# HELP reliacode_http_request_duration_seconds HTTP request latency.","# TYPE reliacode_http_request_duration_seconds histogram"];for(const [key,value] of observations){buckets.forEach((limit,index)=>lines.push(`reliacode_http_request_duration_seconds_bucket{${key},le="${limit}"} ${value.buckets[index]}`));lines.push(`reliacode_http_request_duration_seconds_bucket{${key},le="+Inf"} ${value.count}`);lines.push(`reliacode_http_request_duration_seconds_sum{${key}} ${value.sum}`);lines.push(`reliacode_http_request_duration_seconds_count{${key}} ${value.count}`);}const gauges=await db.query(`SELECT
    (SELECT count(*) FROM event_outbox WHERE processed_at IS NULL AND dead_lettered_at IS NULL)::bigint epcis_backlog,
    (SELECT count(*) FROM event_outbox WHERE processed_at IS NULL AND dead_lettered_at IS NOT NULL)::bigint epcis_dead_letters,
    (SELECT count(*) FROM code_generation_jobs WHERE status IN ('QUEUED','RUNNING'))::bigint code_job_backlog,
    (SELECT count(*) FROM code_generation_jobs WHERE status='COMPLETED' AND export_status IN ('PENDING','EXPORTING','FAILED'))::bigint code_export_backlog,
    (SELECT count(*) FROM code_generation_jobs WHERE export_status='DEAD_LETTER')::bigint code_export_dead_letters,
    (SELECT count(*) FROM webhook_deliveries WHERE status IN ('PENDING','FAILED'))::bigint webhook_backlog,
    (SELECT count(*) FROM webhook_deliveries WHERE status='DEAD_LETTER')::bigint webhook_dead_letters,
    COALESCE((SELECT extract(epoch FROM now()-max(completed_at)) FROM backup_runs WHERE status IN ('COMPLETED','VERIFIED','RESTORED')),-1)::bigint backup_age_seconds`);const row=gauges.rows[0]||{};for(const [name,help] of [["epcis_backlog","Pending OpenEPCIS events"],["epcis_dead_letters","Isolated OpenEPCIS dead letters"],["code_job_backlog","Queued or running code jobs"],["code_export_backlog","Pending or failed code exports"],["code_export_dead_letters","Isolated code export dead letters"],["webhook_backlog","Pending or failed webhook deliveries"],["webhook_dead_letters","Isolated webhook dead letters"],["backup_age_seconds","Age of the newest successful offsite backup, or -1 when absent"]]){lines.push(`# HELP reliacode_${name} ${help}.`,`# TYPE reliacode_${name} gauge`,`reliacode_${name} ${Number(row[name]??-1)}`);}return lines.join("\n")+"\n";}
