import { generateAuthenticationOptions, generateRegistrationOptions, verifyAuthenticationResponse, verifyRegistrationResponse } from "@simplewebauthn/server";
import { randomBytes } from "node:crypto";
import { z } from "zod";
import { hashToken, newSessionToken } from "./auth.mjs";

function normalized(value){return String(value).trim().toLowerCase();}
function webauthnConfig(config){
  const origin=config.WEBAUTHN_ORIGIN || config.corsOrigins[0];
  if(!origin)throw Object.assign(new Error("WebAuthn origin is not configured"),{statusCode:503,code:"PASSKEY_NOT_CONFIGURED"});
  return {origin,rpID:config.WEBAUTHN_RP_ID || new URL(origin).hostname,rpName:config.WEBAUTHN_RP_NAME};
}
function cookies(config,token,csrf){const secure=config.SESSION_COOKIE_SECURE?"; Secure":"";const age=config.SESSION_TTL_HOURS*3600;return [config.SESSION_COOKIE_NAME+"="+token+"; Path=/; HttpOnly; SameSite=Strict; Max-Age="+age+secure,config.CSRF_COOKIE_NAME+"="+csrf+"; Path=/; SameSite=Strict; Max-Age="+age+secure];}
async function session(db,config,userId){const token=newSessionToken(),csrf=newSessionToken();await db.query("INSERT INTO admin_sessions(token_hash,csrf_token_hash,user_id,expires_at) VALUES($1,$2,$3,now()+($4::text||' hours')::interval)",[hashToken(token),hashToken(csrf),userId,String(config.SESSION_TTL_HOURS)]);return{token,csrf};}
async function storeChallenge(db,{challenge,userId,purpose}){await db.query("DELETE FROM webauthn_challenges WHERE expires_at<=now() OR used_at IS NOT NULL");await db.query("INSERT INTO webauthn_challenges(challenge_hash,user_id,purpose,expires_at) VALUES($1,$2,$3,now()+interval '5 minutes')",[hashToken(challenge),userId,purpose]);}
async function consumeChallenge(client,challenge,purpose){const result=await client.query("UPDATE webauthn_challenges SET used_at=now() WHERE challenge_hash=$1 AND purpose=$2 AND used_at IS NULL AND expires_at>now() RETURNING user_id",[hashToken(challenge),purpose]);if(!result.rowCount){const e=new Error("Passkey challenge is invalid or expired");e.statusCode=400;e.code="PASSKEY_CHALLENGE_INVALID";throw e;}return result.rows[0];}

export function registerPasskeyRoutes(app,{db,config}){
  app.get("/api/auth/passkeys",async(request)=>{const result=await db.query("SELECT id,name,transports,device_type,backed_up,last_used_at,created_at FROM webauthn_credentials WHERE user_id=$1 ORDER BY created_at DESC",[request.principal.id]);return{items:result.rows};});
  app.post("/api/auth/passkeys/registration/options",async(request)=>{
    if(config.AUTH_MODE!=="local")throw Object.assign(new Error("Route not found"),{statusCode:404,code:"NOT_FOUND"});
    const user=await db.query("SELECT id,username FROM local_users WHERE id=$1 AND status='ACTIVE'",[request.principal.id]);if(!user.rowCount)throw Object.assign(new Error("User not found"),{statusCode:404,code:"NOT_FOUND"});
    const credentials=await db.query("SELECT id,transports FROM webauthn_credentials WHERE user_id=$1",[request.principal.id]);
    const wc=webauthnConfig(config);
    const options=await generateRegistrationOptions({rpName:wc.rpName,rpID:wc.rpID,userName:user.rows[0].username,userID:new TextEncoder().encode(user.rows[0].id),attestationType:"none",excludeCredentials:credentials.rows.map(row=>({id:row.id,transports:row.transports})),authenticatorSelection:{residentKey:"required",userVerification:"required"}});
    await storeChallenge(db,{challenge:options.challenge,userId:request.principal.id,purpose:"REGISTRATION"});return options;
  });
  app.post("/api/auth/passkeys/registration/verify",async(request,reply)=>{
    const body=z.object({challenge:z.string().min(20),name:z.string().trim().min(1).max(80).default("Passkey"),response:z.record(z.string(),z.unknown())}).parse(request.body);const wc=webauthnConfig(config);
    const result=await db.transaction(async(client)=>{const challenge=await consumeChallenge(client,body.challenge,"REGISTRATION");if(String(challenge.user_id)!==request.principal.id)throw Object.assign(new Error("Passkey challenge belongs to another user"),{statusCode:404,code:"NOT_FOUND"});const verification=await verifyRegistrationResponse({response:body.response,expectedChallenge:body.challenge,expectedOrigin:wc.origin,expectedRPID:wc.rpID,requireUserVerification:true});if(!verification.verified||!verification.registrationInfo)throw Object.assign(new Error("Passkey registration could not be verified"),{statusCode:400,code:"PASSKEY_VERIFICATION_FAILED"});const info=verification.registrationInfo;await client.query(`INSERT INTO webauthn_credentials(id,user_id,public_key,counter,transports,device_type,backed_up,name) VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,[info.credential.id,request.principal.id,Buffer.from(info.credential.publicKey),info.credential.counter,info.credential.transports||[],info.credentialDeviceType,info.credentialBackedUp,body.name]);return{id:info.credential.id,name:body.name};});return reply.code(201).send({verified:true,credential:result});
  });
  app.post("/api/auth/passkeys/authentication/options",{config:{rateLimit:{max:20,timeWindow:"5 minutes"}}},async(request)=>{
    const body=z.object({username:z.string().trim().min(1).max(254)}).parse(request.body);const found=await db.query("SELECT id FROM local_users WHERE (normalized_username=$1 OR normalized_email=$1) AND status='ACTIVE'",[normalized(body.username)]);const user=found.rows[0];const credentials=user?await db.query("SELECT id,transports FROM webauthn_credentials WHERE user_id=$1",[user.id]):{rows:[]};const wc=webauthnConfig(config);const options=await generateAuthenticationOptions({rpID:wc.rpID,userVerification:"required",allowCredentials:credentials.rows.map(row=>({id:row.id,transports:row.transports}))});await storeChallenge(db,{challenge:options.challenge,userId:user?.id||null,purpose:"AUTHENTICATION"});return options;
  });
  app.post("/api/auth/passkeys/authentication/verify",{config:{rateLimit:{max:20,timeWindow:"5 minutes"}}},async(request,reply)=>{
    const body=z.object({challenge:z.string().min(20),response:z.record(z.string(),z.unknown())}).parse(request.body);const wc=webauthnConfig(config);
    const userId=await db.transaction(async(client)=>{const challenge=await consumeChallenge(client,body.challenge,"AUTHENTICATION");if(!challenge.user_id)throw Object.assign(new Error("Passkey authentication failed"),{statusCode:401,code:"INVALID_CREDENTIALS"});const credential=await client.query(`SELECT c.*,u.status user_status FROM webauthn_credentials c JOIN local_users u ON u.id=c.user_id WHERE c.id=$1 AND c.user_id=$2`,[body.response.id,challenge.user_id]);if(!credential.rowCount||credential.rows[0].user_status!=="ACTIVE")throw Object.assign(new Error("Passkey authentication failed"),{statusCode:401,code:"INVALID_CREDENTIALS"});const row=credential.rows[0];const verification=await verifyAuthenticationResponse({response:body.response,expectedChallenge:body.challenge,expectedOrigin:wc.origin,expectedRPID:wc.rpID,credential:{id:row.id,publicKey:new Uint8Array(row.public_key),counter:Number(row.counter),transports:row.transports},requireUserVerification:true});if(!verification.verified)throw Object.assign(new Error("Passkey authentication failed"),{statusCode:401,code:"INVALID_CREDENTIALS"});await client.query("UPDATE webauthn_credentials SET counter=$1,last_used_at=now() WHERE id=$2",[verification.authenticationInfo.newCounter,row.id]);return row.user_id;});const created=await session(db,config,userId);reply.header("set-cookie",cookies(config,created.token,created.csrf));return{authenticated:true,csrfToken:created.csrf};
  });
  app.post("/api/auth/recovery-codes",async(request,reply)=>{
    const body=z.object({reason:z.string().trim().min(3).max(500)}).parse(request.body);const codes=Array.from({length:10},()=>randomBytes(9).toString("base64url").toUpperCase());await db.transaction(async(client)=>{await client.query("DELETE FROM account_recovery_codes WHERE user_id=$1",[request.principal.id]);for(const code of codes)await client.query("INSERT INTO account_recovery_codes(user_id,code_hash) VALUES($1,$2)",[request.principal.id,hashToken(code)]);await client.query(`INSERT INTO audit_log(tenant_id,actor_id,actor_role,organization_id,action,entity_type,entity_id,request_id,after_state) VALUES($1,$2,$3,$4,'RECOVERY_CODES_ROTATED','LOCAL_USER',$2,$5,$6)`,[request.principal.tenantId,request.principal.id,request.principal.role,request.principal.organizationId,request.id,{reason:body.reason,count:codes.length}]);});return reply.code(201).send({codes});
  });
  app.get("/api/auth/sessions",async(request)=>{const result=await db.query("SELECT id,created_at,last_seen_at,expires_at,(token_hash=$2) current FROM admin_sessions WHERE user_id=$1 AND expires_at>now() ORDER BY last_seen_at DESC",[request.principal.id,request.authSession.token_hash]);return{items:result.rows};});
  app.delete("/api/auth/sessions/:id",async(request,reply)=>{const id=z.string().uuid().parse(request.params.id);const removed=await db.query("DELETE FROM admin_sessions WHERE id=$1 AND user_id=$2 RETURNING id",[id,request.principal.id]);if(!removed.rowCount)return reply.code(404).send({code:"NOT_FOUND",message:"Session not found"});return reply.code(204).send();});
  app.post("/api/auth/sessions/revoke-others",async(request)=>{const result=await db.query("DELETE FROM admin_sessions WHERE user_id=$1 AND token_hash<>$2",[request.principal.id,request.authSession.token_hash]);return{revoked:result.rowCount};});
}
