import { loadConfig } from "./config.mjs";
import { createDatabase } from "./db.mjs";
import { decryptWebhookSecret,resolveSafeWebhookUrl,webhookSignature } from "./webhook-security.mjs";
import { pathToFileURL } from "node:url";
import { request as httpsRequest } from "node:https";

export async function claimWebhookDelivery(db){return db.transaction(async client=>{const selected=await client.query(`SELECT d.*,e.url,e.encrypted_secret FROM webhook_deliveries d JOIN webhook_endpoints e ON e.id=d.endpoint_id AND e.tenant_id=d.tenant_id
 WHERE d.status IN ('PENDING','FAILED') AND e.status='ACTIVE' AND d.available_at<=now() AND (d.locked_at IS NULL OR d.locked_at<now()-interval '5 minutes')
 ORDER BY d.created_at LIMIT 1 FOR UPDATE OF d SKIP LOCKED`);if(!selected.rowCount)return null;await client.query("UPDATE webhook_deliveries SET locked_at=now() WHERE id=$1",[selected.rows[0].id]);return selected.rows[0];});}

function pinnedPost(url,addresses,options){return new Promise((resolve,reject)=>{const target=addresses[0],request=httpsRequest(url,{method:"POST",headers:options.headers,servername:url.hostname.replace(/^\[|\]$/g,""),lookup:(_hostname,_options,callback)=>callback(null,target.address,target.family),timeout:10_000},response=>{response.resume();response.on("end",()=>resolve({status:response.statusCode||0}));});request.on("timeout",()=>request.destroy(new Error("Webhook request timed out")));request.on("error",reject);request.end(options.body);});}

export async function processWebhookDelivery(db,config,row,{fetchImpl,lookup}={}){try{const {url,addresses}=await resolveSafeWebhookUrl(row.url,{...(lookup?{lookup}:{})}),secret=decryptWebhookSecret(row.encrypted_secret,config.WEBHOOK_ENCRYPTION_KEY),body=JSON.stringify(row.payload),timestamp=Math.floor(Date.now()/1000).toString(),options={method:"POST",redirect:"error",headers:{"content-type":"application/json","content-length":Buffer.byteLength(body),"user-agent":"ReliaCode-Webhook/1.0","x-reliacode-delivery":row.id,"x-reliacode-event":row.event_type,"x-reliacode-timestamp":timestamp,"x-reliacode-signature":webhookSignature(secret,timestamp,body)},body,signal:AbortSignal.timeout(10_000)};const response=fetchImpl?await fetchImpl(url,options):await pinnedPost(url,addresses,options);if(response.status>=200&&response.status<300){await db.query("UPDATE webhook_deliveries SET status='DELIVERED',delivered_at=now(),locked_at=NULL,last_error=NULL WHERE id=$1",[row.id]);return;}if(response.status===410)await db.query("UPDATE webhook_endpoints SET status='REVOKED' WHERE tenant_id=$1 AND id=$2",[row.tenant_id,row.endpoint_id]);throw new Error(`Webhook returned ${response.status}`);}catch(error){await db.query(`UPDATE webhook_deliveries SET attempts=attempts+1,locked_at=NULL,last_error=$2,
 status=CASE WHEN attempts+1>=10 THEN 'DEAD_LETTER' ELSE 'FAILED' END,dead_lettered_at=CASE WHEN attempts+1>=10 THEN now() ELSE NULL END,
 available_at=now()+(LEAST(3600,power(2,LEAST(attempts+1,11)))::text||' seconds')::interval WHERE id=$1`,[row.id,String(error.message).slice(0,1000)]);}}

if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){const config=loadConfig();if(!config.WEBHOOK_ENCRYPTION_KEY)throw new Error("WEBHOOK_ENCRYPTION_KEY is required for the webhook worker");const db=createDatabase(config);let stopping=false;process.on("SIGTERM",()=>{stopping=true;});process.on("SIGINT",()=>{stopping=true;});try{while(!stopping){const row=await claimWebhookDelivery(db);if(row)await processWebhookDelivery(db,config,row);else await new Promise(resolve=>setTimeout(resolve,1000));}}finally{await db.close();}}
