import { randomBytes } from "node:crypto";
import { z } from "zod";
import { hashToken,requireCapability } from "./auth.mjs";
import { getIdempotentResponse,lockIdempotencyKey,requestHash,saveIdempotentResponse } from "./idempotency.mjs";
import { parseIdempotencyKey } from "./schemas.mjs";
import { assertSafeWebhookUrl,encryptWebhookSecret } from "./webhook-security.mjs";

const uuid=z.string().uuid(),reason=z.string().trim().min(3).max(500);
const eventType=z.enum(["PACKING","UNPACKING","SHIPPING","RECEIVING_DISTRIBUTOR","RECEIVING_STORE","RETURNING","SELLING","DESTROYING","RECALL_ACTIVATED","RISK_CASE_UPDATED"]);
function unavailable(){const error=new Error("Webhook encryption is not configured");error.statusCode=503;error.code="WEBHOOK_NOT_CONFIGURED";throw error;}
function notFound(){const error=new Error("Webhook endpoint not found");error.statusCode=404;error.code="NOT_FOUND";throw error;}
async function tx(db,work){return typeof db.transaction==="function"?db.transaction(work):work(db);}
async function audit(client,request,action,id,before,after){await client.query(`INSERT INTO audit_log(tenant_id,actor_id,actor_role,organization_id,action,entity_type,entity_id,request_id,before_state,after_state)
 VALUES($1,$2,$3,$4,$5,'WEBHOOK_ENDPOINT',$6,$7,$8,$9)`,[request.principal.tenantId,request.principal.id,request.principal.role,request.principal.organizationId,action,String(id),request.id,before,after]);}
async function command(db,request,operation,input,work){const key=parseIdempotencyKey(request),hash=requestHash(operation,input);return tx(db,async client=>{await lockIdempotencyKey(client,request.principal.tenantId,key);const cached=await getIdempotentResponse(client,request.principal.tenantId,key,hash);if(cached)return cached;const result=await work(client);await saveIdempotentResponse(client,{tenantId:request.principal.tenantId,key,operation,hash,status:result.status||200,body:result.value});return{status:result.status||200,body:result.value};});}

export function registerWebhookRoutes(app,{db,config}){
  app.get("/api/v1/integrations/webhooks",async(request)=>{requireCapability(request.principal,"integrations:write");const result=await db.query("SELECT id,url,event_types,status,created_by,created_at FROM webhook_endpoints WHERE tenant_id=$1 ORDER BY created_at DESC",[request.principal.tenantId]);return{items:result.rows};});
  app.post("/api/v1/integrations/webhooks",async(request,reply)=>{requireCapability(request.principal,"integrations:write");if(!config.WEBHOOK_ENCRYPTION_KEY)unavailable();const body=z.object({url:z.string().url().max(2000),eventTypes:z.array(eventType).min(1).max(20),auditReason:reason}).parse(request.body);const safeUrl=await assertSafeWebhookUrl(body.url);const key=parseIdempotencyKey(request),hash=requestHash("WEBHOOK_CREATE",body);const response=await tx(db,async client=>{await lockIdempotencyKey(client,request.principal.tenantId,key);const cached=await getIdempotentResponse(client,request.principal.tenantId,key,hash);if(cached)return cached;const secret=randomBytes(32).toString("base64url"),encrypted=encryptWebhookSecret(secret,config.WEBHOOK_ENCRYPTION_KEY);const created=await client.query(`INSERT INTO webhook_endpoints(tenant_id,url,secret_hash,encrypted_secret,event_types,created_by) VALUES($1,$2,$3,$4,$5,$6)
       RETURNING id,url,event_types,status,created_by,created_at`,[request.principal.tenantId,safeUrl.href,hashToken(secret),encrypted,[...new Set(body.eventTypes)],request.principal.id]);await audit(client,request,"WEBHOOK_CREATE",created.rows[0].id,null,created.rows[0]);const stored={endpoint:created.rows[0],signingSecret:null,secretPreviouslyIssued:true};await saveIdempotentResponse(client,{tenantId:request.principal.tenantId,key,operation:"WEBHOOK_CREATE",hash,status:201,body:stored});return{status:201,body:{endpoint:created.rows[0],signingSecret:secret,secretPreviouslyIssued:false}};});return reply.code(response.status).send(response.body);});
  app.post("/api/v1/integrations/webhooks/:id/revoke",async(request,reply)=>{requireCapability(request.principal,"integrations:write");const id=uuid.parse(request.params.id),body=z.object({auditReason:reason}).parse(request.body);const response=await command(db,request,"WEBHOOK_REVOKE",{id,...body},async client=>{const found=await client.query("SELECT * FROM webhook_endpoints WHERE tenant_id=$1 AND id=$2 FOR UPDATE",[request.principal.tenantId,id]);if(!found.rowCount)notFound();if(found.rows[0].status==="REVOKED")return{value:{id,status:"REVOKED"}};const changed=await client.query("UPDATE webhook_endpoints SET status='REVOKED' WHERE tenant_id=$1 AND id=$2 RETURNING id,url,event_types,status,created_by,created_at",[request.principal.tenantId,id]);await audit(client,request,"WEBHOOK_REVOKE",id,found.rows[0],changed.rows[0]);return{value:changed.rows[0]};});return reply.code(response.status).send(response.body);});
}
